package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/antch57/goose/graph/model"
)

// Albums is the resolver for the albums field.
func (r *bandResolver) Albums(ctx context.Context, obj *model.Band) ([]*model.Album, error) {
	res, err := r.AlbumRepo.GetAlbumsByBandId(obj.ID)
	if err != nil {
		return nil, err
	}

	return res, nil
}

// Band returns BandResolver implementation.
func (r *Resolver) Band() BandResolver { return &bandResolver{r} }

type bandResolver struct{ *Resolver }
