package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"
	"time"

	"github.com/antch57/jam-statz/graph/model"
)

// Band is the resolver for the band field.
func (r *performanceResolver) Band(ctx context.Context, obj *model.Performance) (*model.Band, error) {
	panic(fmt.Errorf("not implemented: Band - band"))
}

// Venue is the resolver for the venue field.
func (r *performanceResolver) Venue(ctx context.Context, obj *model.Performance) (*model.Venue, error) {
	panic(fmt.Errorf("not implemented: Venue - venue"))
}

// Duration is the resolver for the duration field.
func (r *performanceResolver) Duration(ctx context.Context, obj *model.Performance) (time.Duration, error) {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// Song is the resolver for the song field.
func (r *performanceSongResolver) Song(ctx context.Context, obj *model.PerformanceSong) (*model.Song, error) {
	panic(fmt.Errorf("not implemented: Song - song"))
}

// Performance is the resolver for the performance field.
func (r *performanceSongResolver) Performance(ctx context.Context, obj *model.PerformanceSong) (*model.Performance, error) {
	panic(fmt.Errorf("not implemented: Performance - performance"))
}

// Venue is the resolver for the venue field.
func (r *performanceInputResolver) Venue(ctx context.Context, obj *model.PerformanceInput, data int) error {
	panic(fmt.Errorf("not implemented: Venue - venue"))
}

// Duration is the resolver for the duration field.
func (r *performanceInputResolver) Duration(ctx context.Context, obj *model.PerformanceInput, data *time.Duration) error {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// Performance returns PerformanceResolver implementation.
func (r *Resolver) Performance() PerformanceResolver { return &performanceResolver{r} }

// PerformanceSong returns PerformanceSongResolver implementation.
func (r *Resolver) PerformanceSong() PerformanceSongResolver { return &performanceSongResolver{r} }

// PerformanceInput returns PerformanceInputResolver implementation.
func (r *Resolver) PerformanceInput() PerformanceInputResolver { return &performanceInputResolver{r} }

type performanceResolver struct{ *Resolver }
type performanceSongResolver struct{ *Resolver }
type performanceInputResolver struct{ *Resolver }
