// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	ReleaseDate string  `json:"releaseDate"`
	Songs       []*Song `json:"songs"`
}

type Band struct {
	ID     *string  `json:"id,omitempty"`
	Name   string   `json:"name"`
	Genre  string   `json:"genre"`
	Albums []*Album `json:"albums"`
	Year   *int     `json:"year,omitempty"`
}

type Bands struct {
	Bands []*Band `json:"bands"`
}

type Mutation struct {
}

type Query struct {
}

type Song struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Duration string `json:"duration"`
}
