// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	ReleaseDate string  `json:"releaseDate"`
	Songs       []*Song `json:"songs"`
}

type AlbumInput struct {
	Title       string       `json:"title"`
	ReleaseDate string       `json:"releaseDate"`
	Songs       []*SongInput `json:"songs"`
}

type Band struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Genre       string   `json:"genre"`
	Albums      []*Album `json:"albums,omitempty"`
	Year        int      `json:"year"`
	Description *string  `json:"description,omitempty"`
}

type Bands struct {
	Bands []*Band `json:"bands,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Song struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Duration int    `json:"duration"`
	Album    *Album `json:"album,omitempty"`
}

type SongInput struct {
	Title    string `json:"title"`
	Duration int    `json:"duration"`
}
